name: twt-bot

services:
  bot:
    build: &app_build
      dockerfile: ./Dockerfile
      target: dev
    working_dir: &app_working_dir /var/app
    command: "bash -c 'pnpm i --frozen-lockfile && pnpx vite-node src/server.ts'"
    environment: &app_environment
      # Startup Config
      NODE_ENV: "development"
      NODE_OPTIONS: "--inspect 0.0.0.0"
      # Server Config
      DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
      DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      DATABASE_URL: "postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@postgres:5432/${POSTGRES_DATABASE:-myapp}?schema=public"
    volumes: &app_volumes
      - ./prisma:/var/app/prisma:cached
      - ./src:/var/app/src:cached
      - ./pnpm-lock.yaml:/var/app/pnpm-lock.yaml:cached
      - ./package.json:/var/app/package.json:cached
      - ./tsconfig.json:/var/app/tsconfig.json:cached
      - ./guild_configs.yml:/var/app/guild_configs.yml:cached
      - bot-node-modules:/var/app/node_modules
    depends_on: &app_depends_on
      - postgres
  studio:
    build: *app_build
    working_dir: *app_working_dir
    command: ["pnpm", "studio"]
    environment: *app_environment
    volumes: *app_volumes
    depends_on: *app_depends_on
    ports:
      - "${PRISMA_STUDIO_PORT:-5555}:5555"
  postgres:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-admin}"
      POSTGRES_DB: "${POSTGRES_DATABASE:-myapp}"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  bot-node-modules: {}
  postgres-data: {}
