"563929079620042773":
  plugins:
    welcomeMessage:
      channel: "563929079620042775" # welcome
      message: |-
        Welcome {member}!
        @everyone feel free to introduce yourselves to each other.

        {member} optionally you may add an {channel:1050073006346612736} if you'd like.
        Some others have made their own as well and you can copy their format if you'd like.
        You're able to update it whenever!

        First, accept the rules.

        Then, before we can grant you a role you must let us know your first name.
        We go by our first names here for the purpose of networking and such!
      withSetNameButton: true
    setName:
      role: "583006205253779456" # Member
    promoteActiveChannels:
      enabledCategories:
        - "563929079620042774" # Text Topics
        - "1090744204457680936" # Langs
        - "1050072750682812466" # Industry Topics
        - "1016164781318742056" # AI Channels
        - "1083481235839529042" # Recommend This
    kudos:
      maxKudo: 1
      maxKudont: 1
      cooldownSeconds: 30
"326507689356165120":
  plugins:
    voiceLogging:
      enabled: true
    kudos:
      maxKudo: 1
      maxKudont: 1
      cooldownSeconds: 30

