"563929079620042773":
  plugins:
    welcomeMessage:
      channel: "563929079620042775"
      message: |-
        Welcome {member}!
        @everyone feel free to introduce yourselves to each other.

        {member} optionally you may add an {channel:589662168430149642} if you'd like.
        Some others have made their own as welland you can copy their format if you'd like.
        You're able to update it whenever!
      withSetNameButton: true
    setName:
      role: "583006205253779456"
